# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-15 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Desarrollador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_desarrollador', models.CharField(max_length=200)),
                ('apellido_desarrollador', models.CharField(max_length=200)),
                ('edad_desarrollador', models.IntegerField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Horas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desarrollador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeTracker.Desarrollador')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tarea', models.CharField(max_length=200)),
                ('desarrollador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeTracker.Desarrollador')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeTracker.Proyecto')),
            ],
        ),
        migrations.AddField(
            model_name='horas',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeTracker.Proyecto'),
        ),
        migrations.AddField(
            model_name='horas',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeTracker.Tarea'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeTracker.Question'),
        ),
    ]
