# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-15 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeTracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desarrollador',
            name='edad_desarrollador',
            field=models.IntegerField(),
        ),
    ]
