# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-16 23:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timeTracker', '0003_auto_20181115_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desarrollador',
            old_name='apellido_desarrollador',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='desarrollador',
            old_name='nombre_desarrollador',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='nombre_proyecto',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='tarea',
            old_name='nombre_tarea',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='desarrollador',
            name='edad_desarrollador',
        ),
        migrations.RemoveField(
            model_name='horas',
            name='desarrollador',
        ),
        migrations.RemoveField(
            model_name='horas',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='desarrollador',
        ),
        migrations.AddField(
            model_name='desarrollador',
            name='edad',
            field=models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='desarrollador',
            name='horas',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='timeTracker.Horas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horas',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='horas',
            name='cantidad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
