# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-17 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeTracker', '0004_auto_20181116_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desarrollador',
            name='horas',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='timeTracker.Horas'),
        ),
    ]
