# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-17 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeTracker', '0007_auto_20181117_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desarrollador',
            name='horas',
        ),
        migrations.AddField(
            model_name='desarrollador',
            name='horas',
            field=models.ManyToManyField(to='timeTracker.Horas'),
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='tareas',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tareas',
            field=models.ManyToManyField(to='timeTracker.Tarea'),
        ),
    ]
