# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-17 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeTracker', '0008_auto_20181117_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='tareas',
        ),
        migrations.AddField(
            model_name='tarea',
            name='tareas',
            field=models.ManyToManyField(to='timeTracker.Proyecto'),
        ),
    ]
