# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-17 22:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeTracker', '0010_auto_20181117_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='tareas',
            new_name='Proyecto',
        ),
    ]
