# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-17 22:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeTracker', '0011_auto_20181117_2242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='Proyecto',
            new_name='proyecto',
        ),
    ]
