# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-17 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeTracker', '0014_auto_20181117_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horas',
            name='desarrollador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timeTracker.Desarrollador'),
        ),
    ]
