# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-11 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeTracker', '0015_auto_20181117_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timeTracker.Desarrollador'),
        ),
    ]
